services:
    _defaults:
        autowire: true
        autoconfigure: true

    2biased.conato.validation.event_listeners:
        namespace: TwoBiased\ContaoValidationBundle\EventListener\
        resource: '../src/EventListener'
